/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { InstallmentPlan, InstallmentPlans, METHODS } from "./types";
export { InstallmentPlan, InstallmentPlans, METHODS } from "./types";
export namespace Components {
    interface EasycreditAccordion {
        /**
          * close an accordion item
          * @param index
         */
        "close": (index: number) => Promise<void>;
        /**
          * Open an accordion item
          * @param index
         */
        "open": (index: number) => Promise<void>;
    }
    interface EasycreditAccordionItem {
        /**
          * close the accordion item
         */
        "closeItem": () => Promise<void>;
        /**
          * index of accordion item from top to bottom
          * @default -1
         */
        "index": number;
        /**
          * The mutation observer config to listen for content changes in the accordion item
          * @default { childList: true, subtree: true }
         */
        "mutationObserverConfig": { childList: boolean; subtree: boolean; };
        /**
          * accordion item is open or opening (css transition)
          * @default false
         */
        "open": boolean;
        /**
          * open the accordion item
         */
        "openItem": () => Promise<void>;
    }
    interface EasycreditBase {
    }
    interface EasycreditBoxFlash {
        /**
          * @default false
         */
        "isOpen": boolean;
        "src": string;
        "toggle": () => Promise<void>;
    }
    interface EasycreditBoxListing {
        "src": string;
        "toggle": () => Promise<void>;
    }
    interface EasycreditBoxModal {
        "delay": number;
        /**
          * @default false
         */
        "isOpen": boolean;
        "snoozeFor": number;
        "src": string;
        "toggle": () => Promise<void>;
    }
    interface EasycreditBoxTop {
    }
    interface EasycreditCheckout {
        "alert": string;
        "amount": number;
        /**
          * @default false
         */
        "disableFlexprice": boolean;
        /**
          * @default true
         */
        "isActive": boolean;
        /**
          * @default false
         */
        "noInteraction": boolean;
        "paymentPlan": string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType": METHODS;
        "webshopId": string;
    }
    interface EasycreditCheckoutBillPaymentTimeline {
    }
    interface EasycreditCheckoutInstallments {
        "installments": any;
        /**
          * @default 5
         */
        "rows": number;
        /**
          * @default 'Weitere Raten anzeigen +'
         */
        "showMoreButtonText": string;
    }
    interface EasycreditCheckoutLabel {
        "label": string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType": METHODS;
        "slogan": string;
    }
    interface EasycreditCheckoutPrivacyApproval {
        "webshopId": string;
    }
    interface EasycreditCheckoutTotals {
        "amount": number;
        /**
          * @default null
         */
        "installmentPlans": InstallmentPlans;
        /**
          * @default null
         */
        "selectedInstallment": InstallmentPlan;
    }
    interface EasycreditExpressButton {
        "amount": number;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "paymentTypes": string;
        "redirectUrl": string;
        "webshopId": string;
    }
    interface EasycreditExpressButtonSingle {
        "amount": number;
        /**
          * @default false
         */
        "bgBlue": boolean;
        /**
          * @default false
         */
        "fullWidth": boolean;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType": METHODS;
        "webshopId": string;
    }
    interface EasycreditFaq {
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType": string;
    }
    interface EasycreditInfopage {
        "paymentTypes": string;
        /**
          * @default 'default'
         */
        "variant": 'default' | 'enhanced';
    }
    interface EasycreditLogo {
        /**
          * @default 'easyCredit-Ratenkauf - Einfach. Fair. In Raten zahlen.'
         */
        "alt": string;
        /**
          * @default 'blue'
         */
        "color": string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType": METHODS;
    }
    interface EasycreditMerchantManager {
        "date": string;
        "txId": string;
    }
    interface EasycreditMerchantStatusWidget {
        "date": string;
        "isManager": boolean;
        "txId": string;
    }
    interface EasycreditModal {
        "close": () => Promise<void>;
        /**
          * @default false
         */
        "isOpen": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default 'Loading...'
         */
        "loadingMessage": string;
        "open": () => Promise<void>;
        "show": boolean;
        /**
          * @default ''
         */
        "size": string;
        "submit": () => Promise<void>;
        "toggle": () => Promise<void>;
    }
    interface EasycreditWidget {
        "amount": number;
        /**
          * @default false
         */
        "disableFlexprice": boolean;
        "displayType": string;
        /**
          * @default true
         */
        "extended": boolean;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentTypes": string;
        "webshopId": string;
    }
}
export interface EasycreditAccordionItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEasycreditAccordionItemElement;
}
export interface EasycreditCheckoutInstallmentsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEasycreditCheckoutInstallmentsElement;
}
export interface EasycreditExpressButtonSingleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEasycreditExpressButtonSingleElement;
}
export interface EasycreditModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEasycreditModalElement;
}
declare global {
    interface HTMLEasycreditAccordionElement extends Components.EasycreditAccordion, HTMLStencilElement {
    }
    var HTMLEasycreditAccordionElement: {
        prototype: HTMLEasycreditAccordionElement;
        new (): HTMLEasycreditAccordionElement;
    };
    interface HTMLEasycreditAccordionItemElementEventMap {
        "openEvent": any;
        "contentChanged": any;
    }
    interface HTMLEasycreditAccordionItemElement extends Components.EasycreditAccordionItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEasycreditAccordionItemElementEventMap>(type: K, listener: (this: HTMLEasycreditAccordionItemElement, ev: EasycreditAccordionItemCustomEvent<HTMLEasycreditAccordionItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEasycreditAccordionItemElementEventMap>(type: K, listener: (this: HTMLEasycreditAccordionItemElement, ev: EasycreditAccordionItemCustomEvent<HTMLEasycreditAccordionItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEasycreditAccordionItemElement: {
        prototype: HTMLEasycreditAccordionItemElement;
        new (): HTMLEasycreditAccordionItemElement;
    };
    interface HTMLEasycreditBaseElement extends Components.EasycreditBase, HTMLStencilElement {
    }
    var HTMLEasycreditBaseElement: {
        prototype: HTMLEasycreditBaseElement;
        new (): HTMLEasycreditBaseElement;
    };
    interface HTMLEasycreditBoxFlashElement extends Components.EasycreditBoxFlash, HTMLStencilElement {
    }
    var HTMLEasycreditBoxFlashElement: {
        prototype: HTMLEasycreditBoxFlashElement;
        new (): HTMLEasycreditBoxFlashElement;
    };
    interface HTMLEasycreditBoxListingElement extends Components.EasycreditBoxListing, HTMLStencilElement {
    }
    var HTMLEasycreditBoxListingElement: {
        prototype: HTMLEasycreditBoxListingElement;
        new (): HTMLEasycreditBoxListingElement;
    };
    interface HTMLEasycreditBoxModalElement extends Components.EasycreditBoxModal, HTMLStencilElement {
    }
    var HTMLEasycreditBoxModalElement: {
        prototype: HTMLEasycreditBoxModalElement;
        new (): HTMLEasycreditBoxModalElement;
    };
    interface HTMLEasycreditBoxTopElement extends Components.EasycreditBoxTop, HTMLStencilElement {
    }
    var HTMLEasycreditBoxTopElement: {
        prototype: HTMLEasycreditBoxTopElement;
        new (): HTMLEasycreditBoxTopElement;
    };
    interface HTMLEasycreditCheckoutElement extends Components.EasycreditCheckout, HTMLStencilElement {
    }
    var HTMLEasycreditCheckoutElement: {
        prototype: HTMLEasycreditCheckoutElement;
        new (): HTMLEasycreditCheckoutElement;
    };
    interface HTMLEasycreditCheckoutBillPaymentTimelineElement extends Components.EasycreditCheckoutBillPaymentTimeline, HTMLStencilElement {
    }
    var HTMLEasycreditCheckoutBillPaymentTimelineElement: {
        prototype: HTMLEasycreditCheckoutBillPaymentTimelineElement;
        new (): HTMLEasycreditCheckoutBillPaymentTimelineElement;
    };
    interface HTMLEasycreditCheckoutInstallmentsElementEventMap {
        "selectedInstallment": string;
    }
    interface HTMLEasycreditCheckoutInstallmentsElement extends Components.EasycreditCheckoutInstallments, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEasycreditCheckoutInstallmentsElementEventMap>(type: K, listener: (this: HTMLEasycreditCheckoutInstallmentsElement, ev: EasycreditCheckoutInstallmentsCustomEvent<HTMLEasycreditCheckoutInstallmentsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEasycreditCheckoutInstallmentsElementEventMap>(type: K, listener: (this: HTMLEasycreditCheckoutInstallmentsElement, ev: EasycreditCheckoutInstallmentsCustomEvent<HTMLEasycreditCheckoutInstallmentsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEasycreditCheckoutInstallmentsElement: {
        prototype: HTMLEasycreditCheckoutInstallmentsElement;
        new (): HTMLEasycreditCheckoutInstallmentsElement;
    };
    interface HTMLEasycreditCheckoutLabelElement extends Components.EasycreditCheckoutLabel, HTMLStencilElement {
    }
    var HTMLEasycreditCheckoutLabelElement: {
        prototype: HTMLEasycreditCheckoutLabelElement;
        new (): HTMLEasycreditCheckoutLabelElement;
    };
    interface HTMLEasycreditCheckoutPrivacyApprovalElement extends Components.EasycreditCheckoutPrivacyApproval, HTMLStencilElement {
    }
    var HTMLEasycreditCheckoutPrivacyApprovalElement: {
        prototype: HTMLEasycreditCheckoutPrivacyApprovalElement;
        new (): HTMLEasycreditCheckoutPrivacyApprovalElement;
    };
    interface HTMLEasycreditCheckoutTotalsElement extends Components.EasycreditCheckoutTotals, HTMLStencilElement {
    }
    var HTMLEasycreditCheckoutTotalsElement: {
        prototype: HTMLEasycreditCheckoutTotalsElement;
        new (): HTMLEasycreditCheckoutTotalsElement;
    };
    interface HTMLEasycreditExpressButtonElement extends Components.EasycreditExpressButton, HTMLStencilElement {
    }
    var HTMLEasycreditExpressButtonElement: {
        prototype: HTMLEasycreditExpressButtonElement;
        new (): HTMLEasycreditExpressButtonElement;
    };
    interface HTMLEasycreditExpressButtonSingleElementEventMap {
        "buttonClicked": string;
    }
    interface HTMLEasycreditExpressButtonSingleElement extends Components.EasycreditExpressButtonSingle, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEasycreditExpressButtonSingleElementEventMap>(type: K, listener: (this: HTMLEasycreditExpressButtonSingleElement, ev: EasycreditExpressButtonSingleCustomEvent<HTMLEasycreditExpressButtonSingleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEasycreditExpressButtonSingleElementEventMap>(type: K, listener: (this: HTMLEasycreditExpressButtonSingleElement, ev: EasycreditExpressButtonSingleCustomEvent<HTMLEasycreditExpressButtonSingleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEasycreditExpressButtonSingleElement: {
        prototype: HTMLEasycreditExpressButtonSingleElement;
        new (): HTMLEasycreditExpressButtonSingleElement;
    };
    interface HTMLEasycreditFaqElement extends Components.EasycreditFaq, HTMLStencilElement {
    }
    var HTMLEasycreditFaqElement: {
        prototype: HTMLEasycreditFaqElement;
        new (): HTMLEasycreditFaqElement;
    };
    interface HTMLEasycreditInfopageElement extends Components.EasycreditInfopage, HTMLStencilElement {
    }
    var HTMLEasycreditInfopageElement: {
        prototype: HTMLEasycreditInfopageElement;
        new (): HTMLEasycreditInfopageElement;
    };
    interface HTMLEasycreditLogoElement extends Components.EasycreditLogo, HTMLStencilElement {
    }
    var HTMLEasycreditLogoElement: {
        prototype: HTMLEasycreditLogoElement;
        new (): HTMLEasycreditLogoElement;
    };
    interface HTMLEasycreditMerchantManagerElement extends Components.EasycreditMerchantManager, HTMLStencilElement {
    }
    var HTMLEasycreditMerchantManagerElement: {
        prototype: HTMLEasycreditMerchantManagerElement;
        new (): HTMLEasycreditMerchantManagerElement;
    };
    interface HTMLEasycreditMerchantStatusWidgetElement extends Components.EasycreditMerchantStatusWidget, HTMLStencilElement {
    }
    var HTMLEasycreditMerchantStatusWidgetElement: {
        prototype: HTMLEasycreditMerchantStatusWidgetElement;
        new (): HTMLEasycreditMerchantStatusWidgetElement;
    };
    interface HTMLEasycreditModalElementEventMap {
        "modalOpened": any;
        "modalClosed": any;
        "modalSubmit": any;
    }
    interface HTMLEasycreditModalElement extends Components.EasycreditModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEasycreditModalElementEventMap>(type: K, listener: (this: HTMLEasycreditModalElement, ev: EasycreditModalCustomEvent<HTMLEasycreditModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEasycreditModalElementEventMap>(type: K, listener: (this: HTMLEasycreditModalElement, ev: EasycreditModalCustomEvent<HTMLEasycreditModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEasycreditModalElement: {
        prototype: HTMLEasycreditModalElement;
        new (): HTMLEasycreditModalElement;
    };
    interface HTMLEasycreditWidgetElement extends Components.EasycreditWidget, HTMLStencilElement {
    }
    var HTMLEasycreditWidgetElement: {
        prototype: HTMLEasycreditWidgetElement;
        new (): HTMLEasycreditWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "easycredit-accordion": HTMLEasycreditAccordionElement;
        "easycredit-accordion-item": HTMLEasycreditAccordionItemElement;
        "easycredit-base": HTMLEasycreditBaseElement;
        "easycredit-box-flash": HTMLEasycreditBoxFlashElement;
        "easycredit-box-listing": HTMLEasycreditBoxListingElement;
        "easycredit-box-modal": HTMLEasycreditBoxModalElement;
        "easycredit-box-top": HTMLEasycreditBoxTopElement;
        "easycredit-checkout": HTMLEasycreditCheckoutElement;
        "easycredit-checkout-bill-payment-timeline": HTMLEasycreditCheckoutBillPaymentTimelineElement;
        "easycredit-checkout-installments": HTMLEasycreditCheckoutInstallmentsElement;
        "easycredit-checkout-label": HTMLEasycreditCheckoutLabelElement;
        "easycredit-checkout-privacy-approval": HTMLEasycreditCheckoutPrivacyApprovalElement;
        "easycredit-checkout-totals": HTMLEasycreditCheckoutTotalsElement;
        "easycredit-express-button": HTMLEasycreditExpressButtonElement;
        "easycredit-express-button-single": HTMLEasycreditExpressButtonSingleElement;
        "easycredit-faq": HTMLEasycreditFaqElement;
        "easycredit-infopage": HTMLEasycreditInfopageElement;
        "easycredit-logo": HTMLEasycreditLogoElement;
        "easycredit-merchant-manager": HTMLEasycreditMerchantManagerElement;
        "easycredit-merchant-status-widget": HTMLEasycreditMerchantStatusWidgetElement;
        "easycredit-modal": HTMLEasycreditModalElement;
        "easycredit-widget": HTMLEasycreditWidgetElement;
    }
}
declare namespace LocalJSX {
    interface EasycreditAccordion {
    }
    interface EasycreditAccordionItem {
        /**
          * index of accordion item from top to bottom
          * @default -1
         */
        "index"?: number;
        /**
          * The mutation observer config to listen for content changes in the accordion item
          * @default { childList: true, subtree: true }
         */
        "mutationObserverConfig"?: { childList: boolean; subtree: boolean; };
        /**
          * triggered when the content of the accordion item changes
         */
        "onContentChanged"?: (event: EasycreditAccordionItemCustomEvent<any>) => void;
        /**
          * triggered when the accordion item is opened
         */
        "onOpenEvent"?: (event: EasycreditAccordionItemCustomEvent<any>) => void;
        /**
          * accordion item is open or opening (css transition)
          * @default false
         */
        "open"?: boolean;
    }
    interface EasycreditBase {
    }
    interface EasycreditBoxFlash {
        /**
          * @default false
         */
        "isOpen"?: boolean;
        "src"?: string;
    }
    interface EasycreditBoxListing {
        "src"?: string;
    }
    interface EasycreditBoxModal {
        "delay"?: number;
        /**
          * @default false
         */
        "isOpen"?: boolean;
        "snoozeFor"?: number;
        "src"?: string;
    }
    interface EasycreditBoxTop {
    }
    interface EasycreditCheckout {
        "alert"?: string;
        "amount"?: number;
        /**
          * @default false
         */
        "disableFlexprice"?: boolean;
        /**
          * @default true
         */
        "isActive"?: boolean;
        /**
          * @default false
         */
        "noInteraction"?: boolean;
        "paymentPlan"?: string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType"?: METHODS;
        "webshopId"?: string;
    }
    interface EasycreditCheckoutBillPaymentTimeline {
    }
    interface EasycreditCheckoutInstallments {
        "installments"?: any;
        "onSelectedInstallment"?: (event: EasycreditCheckoutInstallmentsCustomEvent<string>) => void;
        /**
          * @default 5
         */
        "rows"?: number;
        /**
          * @default 'Weitere Raten anzeigen +'
         */
        "showMoreButtonText"?: string;
    }
    interface EasycreditCheckoutLabel {
        "label"?: string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType"?: METHODS;
        "slogan"?: string;
    }
    interface EasycreditCheckoutPrivacyApproval {
        "webshopId"?: string;
    }
    interface EasycreditCheckoutTotals {
        "amount"?: number;
        /**
          * @default null
         */
        "installmentPlans"?: InstallmentPlans;
        /**
          * @default null
         */
        "selectedInstallment"?: InstallmentPlan;
    }
    interface EasycreditExpressButton {
        "amount"?: number;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "paymentTypes"?: string;
        "redirectUrl"?: string;
        "webshopId"?: string;
    }
    interface EasycreditExpressButtonSingle {
        "amount"?: number;
        /**
          * @default false
         */
        "bgBlue"?: boolean;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "onButtonClicked"?: (event: EasycreditExpressButtonSingleCustomEvent<string>) => void;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType"?: METHODS;
        "webshopId"?: string;
    }
    interface EasycreditFaq {
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType"?: string;
    }
    interface EasycreditInfopage {
        "paymentTypes"?: string;
        /**
          * @default 'default'
         */
        "variant"?: 'default' | 'enhanced';
    }
    interface EasycreditLogo {
        /**
          * @default 'easyCredit-Ratenkauf - Einfach. Fair. In Raten zahlen.'
         */
        "alt"?: string;
        /**
          * @default 'blue'
         */
        "color"?: string;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentType"?: METHODS;
    }
    interface EasycreditMerchantManager {
        "date"?: string;
        "txId"?: string;
    }
    interface EasycreditMerchantStatusWidget {
        "date"?: string;
        "isManager"?: boolean;
        "txId"?: string;
    }
    interface EasycreditModal {
        /**
          * @default false
         */
        "isOpen"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * @default 'Loading...'
         */
        "loadingMessage"?: string;
        "onModalClosed"?: (event: EasycreditModalCustomEvent<any>) => void;
        "onModalOpened"?: (event: EasycreditModalCustomEvent<any>) => void;
        "onModalSubmit"?: (event: EasycreditModalCustomEvent<any>) => void;
        "show"?: boolean;
        /**
          * @default ''
         */
        "size"?: string;
    }
    interface EasycreditWidget {
        "amount"?: number;
        /**
          * @default false
         */
        "disableFlexprice"?: boolean;
        "displayType"?: string;
        /**
          * @default true
         */
        "extended"?: boolean;
        /**
          * @default METHODS.INSTALLMENT
         */
        "paymentTypes"?: string;
        "webshopId"?: string;
    }

    interface EasycreditAccordionItemAttributes {
        "index": number;
        "open": boolean;
    }
    interface EasycreditBoxFlashAttributes {
        "src": string;
        "isOpen": boolean;
    }
    interface EasycreditBoxListingAttributes {
        "src": string;
    }
    interface EasycreditBoxModalAttributes {
        "src": string;
        "snoozeFor": number;
        "delay": number;
        "isOpen": boolean;
    }
    interface EasycreditCheckoutAttributes {
        "isActive": boolean;
        "amount": number;
        "webshopId": string;
        "alert": string;
        "paymentPlan": string;
        "paymentType": METHODS;
        "disableFlexprice": boolean;
        "noInteraction": boolean;
    }
    interface EasycreditCheckoutInstallmentsAttributes {
        "showMoreButtonText": string;
        "installments": string;
        "rows": number;
    }
    interface EasycreditCheckoutLabelAttributes {
        "label": string;
        "slogan": string;
        "paymentType": METHODS;
    }
    interface EasycreditCheckoutPrivacyApprovalAttributes {
        "webshopId": string;
    }
    interface EasycreditCheckoutTotalsAttributes {
        "amount": number;
    }
    interface EasycreditExpressButtonAttributes {
        "webshopId": string;
        "amount": number;
        "paymentTypes": string;
        "fullWidth": boolean;
        "redirectUrl": string;
    }
    interface EasycreditExpressButtonSingleAttributes {
        "webshopId": string;
        "amount": number;
        "bgBlue": boolean;
        "fullWidth": boolean;
        "paymentType": METHODS;
    }
    interface EasycreditFaqAttributes {
        "paymentType": string;
    }
    interface EasycreditInfopageAttributes {
        "paymentTypes": string;
        "variant": 'default' | 'enhanced';
    }
    interface EasycreditLogoAttributes {
        "paymentType": METHODS;
        "color": string;
        "alt": string;
    }
    interface EasycreditMerchantManagerAttributes {
        "txId": string;
        "date": string;
    }
    interface EasycreditMerchantStatusWidgetAttributes {
        "txId": string;
        "date": string;
        "isManager": boolean;
    }
    interface EasycreditModalAttributes {
        "loading": boolean;
        "loadingMessage": string;
        "show": boolean;
        "isOpen": boolean;
        "size": string;
    }
    interface EasycreditWidgetAttributes {
        "webshopId": string;
        "amount": number;
        "displayType": string;
        "paymentTypes": string;
        "extended": boolean;
        "disableFlexprice": boolean;
    }

    interface IntrinsicElements {
        "easycredit-accordion": EasycreditAccordion;
        "easycredit-accordion-item": Omit<EasycreditAccordionItem, keyof EasycreditAccordionItemAttributes> & { [K in keyof EasycreditAccordionItem & keyof EasycreditAccordionItemAttributes]?: EasycreditAccordionItem[K] } & { [K in keyof EasycreditAccordionItem & keyof EasycreditAccordionItemAttributes as `attr:${K}`]?: EasycreditAccordionItemAttributes[K] } & { [K in keyof EasycreditAccordionItem & keyof EasycreditAccordionItemAttributes as `prop:${K}`]?: EasycreditAccordionItem[K] };
        "easycredit-base": EasycreditBase;
        "easycredit-box-flash": Omit<EasycreditBoxFlash, keyof EasycreditBoxFlashAttributes> & { [K in keyof EasycreditBoxFlash & keyof EasycreditBoxFlashAttributes]?: EasycreditBoxFlash[K] } & { [K in keyof EasycreditBoxFlash & keyof EasycreditBoxFlashAttributes as `attr:${K}`]?: EasycreditBoxFlashAttributes[K] } & { [K in keyof EasycreditBoxFlash & keyof EasycreditBoxFlashAttributes as `prop:${K}`]?: EasycreditBoxFlash[K] };
        "easycredit-box-listing": Omit<EasycreditBoxListing, keyof EasycreditBoxListingAttributes> & { [K in keyof EasycreditBoxListing & keyof EasycreditBoxListingAttributes]?: EasycreditBoxListing[K] } & { [K in keyof EasycreditBoxListing & keyof EasycreditBoxListingAttributes as `attr:${K}`]?: EasycreditBoxListingAttributes[K] } & { [K in keyof EasycreditBoxListing & keyof EasycreditBoxListingAttributes as `prop:${K}`]?: EasycreditBoxListing[K] };
        "easycredit-box-modal": Omit<EasycreditBoxModal, keyof EasycreditBoxModalAttributes> & { [K in keyof EasycreditBoxModal & keyof EasycreditBoxModalAttributes]?: EasycreditBoxModal[K] } & { [K in keyof EasycreditBoxModal & keyof EasycreditBoxModalAttributes as `attr:${K}`]?: EasycreditBoxModalAttributes[K] } & { [K in keyof EasycreditBoxModal & keyof EasycreditBoxModalAttributes as `prop:${K}`]?: EasycreditBoxModal[K] };
        "easycredit-box-top": EasycreditBoxTop;
        "easycredit-checkout": Omit<EasycreditCheckout, keyof EasycreditCheckoutAttributes> & { [K in keyof EasycreditCheckout & keyof EasycreditCheckoutAttributes]?: EasycreditCheckout[K] } & { [K in keyof EasycreditCheckout & keyof EasycreditCheckoutAttributes as `attr:${K}`]?: EasycreditCheckoutAttributes[K] } & { [K in keyof EasycreditCheckout & keyof EasycreditCheckoutAttributes as `prop:${K}`]?: EasycreditCheckout[K] };
        "easycredit-checkout-bill-payment-timeline": EasycreditCheckoutBillPaymentTimeline;
        "easycredit-checkout-installments": Omit<EasycreditCheckoutInstallments, keyof EasycreditCheckoutInstallmentsAttributes> & { [K in keyof EasycreditCheckoutInstallments & keyof EasycreditCheckoutInstallmentsAttributes]?: EasycreditCheckoutInstallments[K] } & { [K in keyof EasycreditCheckoutInstallments & keyof EasycreditCheckoutInstallmentsAttributes as `attr:${K}`]?: EasycreditCheckoutInstallmentsAttributes[K] } & { [K in keyof EasycreditCheckoutInstallments & keyof EasycreditCheckoutInstallmentsAttributes as `prop:${K}`]?: EasycreditCheckoutInstallments[K] };
        "easycredit-checkout-label": Omit<EasycreditCheckoutLabel, keyof EasycreditCheckoutLabelAttributes> & { [K in keyof EasycreditCheckoutLabel & keyof EasycreditCheckoutLabelAttributes]?: EasycreditCheckoutLabel[K] } & { [K in keyof EasycreditCheckoutLabel & keyof EasycreditCheckoutLabelAttributes as `attr:${K}`]?: EasycreditCheckoutLabelAttributes[K] } & { [K in keyof EasycreditCheckoutLabel & keyof EasycreditCheckoutLabelAttributes as `prop:${K}`]?: EasycreditCheckoutLabel[K] };
        "easycredit-checkout-privacy-approval": Omit<EasycreditCheckoutPrivacyApproval, keyof EasycreditCheckoutPrivacyApprovalAttributes> & { [K in keyof EasycreditCheckoutPrivacyApproval & keyof EasycreditCheckoutPrivacyApprovalAttributes]?: EasycreditCheckoutPrivacyApproval[K] } & { [K in keyof EasycreditCheckoutPrivacyApproval & keyof EasycreditCheckoutPrivacyApprovalAttributes as `attr:${K}`]?: EasycreditCheckoutPrivacyApprovalAttributes[K] } & { [K in keyof EasycreditCheckoutPrivacyApproval & keyof EasycreditCheckoutPrivacyApprovalAttributes as `prop:${K}`]?: EasycreditCheckoutPrivacyApproval[K] };
        "easycredit-checkout-totals": Omit<EasycreditCheckoutTotals, keyof EasycreditCheckoutTotalsAttributes> & { [K in keyof EasycreditCheckoutTotals & keyof EasycreditCheckoutTotalsAttributes]?: EasycreditCheckoutTotals[K] } & { [K in keyof EasycreditCheckoutTotals & keyof EasycreditCheckoutTotalsAttributes as `attr:${K}`]?: EasycreditCheckoutTotalsAttributes[K] } & { [K in keyof EasycreditCheckoutTotals & keyof EasycreditCheckoutTotalsAttributes as `prop:${K}`]?: EasycreditCheckoutTotals[K] };
        "easycredit-express-button": Omit<EasycreditExpressButton, keyof EasycreditExpressButtonAttributes> & { [K in keyof EasycreditExpressButton & keyof EasycreditExpressButtonAttributes]?: EasycreditExpressButton[K] } & { [K in keyof EasycreditExpressButton & keyof EasycreditExpressButtonAttributes as `attr:${K}`]?: EasycreditExpressButtonAttributes[K] } & { [K in keyof EasycreditExpressButton & keyof EasycreditExpressButtonAttributes as `prop:${K}`]?: EasycreditExpressButton[K] };
        "easycredit-express-button-single": Omit<EasycreditExpressButtonSingle, keyof EasycreditExpressButtonSingleAttributes> & { [K in keyof EasycreditExpressButtonSingle & keyof EasycreditExpressButtonSingleAttributes]?: EasycreditExpressButtonSingle[K] } & { [K in keyof EasycreditExpressButtonSingle & keyof EasycreditExpressButtonSingleAttributes as `attr:${K}`]?: EasycreditExpressButtonSingleAttributes[K] } & { [K in keyof EasycreditExpressButtonSingle & keyof EasycreditExpressButtonSingleAttributes as `prop:${K}`]?: EasycreditExpressButtonSingle[K] };
        "easycredit-faq": Omit<EasycreditFaq, keyof EasycreditFaqAttributes> & { [K in keyof EasycreditFaq & keyof EasycreditFaqAttributes]?: EasycreditFaq[K] } & { [K in keyof EasycreditFaq & keyof EasycreditFaqAttributes as `attr:${K}`]?: EasycreditFaqAttributes[K] } & { [K in keyof EasycreditFaq & keyof EasycreditFaqAttributes as `prop:${K}`]?: EasycreditFaq[K] };
        "easycredit-infopage": Omit<EasycreditInfopage, keyof EasycreditInfopageAttributes> & { [K in keyof EasycreditInfopage & keyof EasycreditInfopageAttributes]?: EasycreditInfopage[K] } & { [K in keyof EasycreditInfopage & keyof EasycreditInfopageAttributes as `attr:${K}`]?: EasycreditInfopageAttributes[K] } & { [K in keyof EasycreditInfopage & keyof EasycreditInfopageAttributes as `prop:${K}`]?: EasycreditInfopage[K] };
        "easycredit-logo": Omit<EasycreditLogo, keyof EasycreditLogoAttributes> & { [K in keyof EasycreditLogo & keyof EasycreditLogoAttributes]?: EasycreditLogo[K] } & { [K in keyof EasycreditLogo & keyof EasycreditLogoAttributes as `attr:${K}`]?: EasycreditLogoAttributes[K] } & { [K in keyof EasycreditLogo & keyof EasycreditLogoAttributes as `prop:${K}`]?: EasycreditLogo[K] };
        "easycredit-merchant-manager": Omit<EasycreditMerchantManager, keyof EasycreditMerchantManagerAttributes> & { [K in keyof EasycreditMerchantManager & keyof EasycreditMerchantManagerAttributes]?: EasycreditMerchantManager[K] } & { [K in keyof EasycreditMerchantManager & keyof EasycreditMerchantManagerAttributes as `attr:${K}`]?: EasycreditMerchantManagerAttributes[K] } & { [K in keyof EasycreditMerchantManager & keyof EasycreditMerchantManagerAttributes as `prop:${K}`]?: EasycreditMerchantManager[K] };
        "easycredit-merchant-status-widget": Omit<EasycreditMerchantStatusWidget, keyof EasycreditMerchantStatusWidgetAttributes> & { [K in keyof EasycreditMerchantStatusWidget & keyof EasycreditMerchantStatusWidgetAttributes]?: EasycreditMerchantStatusWidget[K] } & { [K in keyof EasycreditMerchantStatusWidget & keyof EasycreditMerchantStatusWidgetAttributes as `attr:${K}`]?: EasycreditMerchantStatusWidgetAttributes[K] } & { [K in keyof EasycreditMerchantStatusWidget & keyof EasycreditMerchantStatusWidgetAttributes as `prop:${K}`]?: EasycreditMerchantStatusWidget[K] };
        "easycredit-modal": Omit<EasycreditModal, keyof EasycreditModalAttributes> & { [K in keyof EasycreditModal & keyof EasycreditModalAttributes]?: EasycreditModal[K] } & { [K in keyof EasycreditModal & keyof EasycreditModalAttributes as `attr:${K}`]?: EasycreditModalAttributes[K] } & { [K in keyof EasycreditModal & keyof EasycreditModalAttributes as `prop:${K}`]?: EasycreditModal[K] };
        "easycredit-widget": Omit<EasycreditWidget, keyof EasycreditWidgetAttributes> & { [K in keyof EasycreditWidget & keyof EasycreditWidgetAttributes]?: EasycreditWidget[K] } & { [K in keyof EasycreditWidget & keyof EasycreditWidgetAttributes as `attr:${K}`]?: EasycreditWidgetAttributes[K] } & { [K in keyof EasycreditWidget & keyof EasycreditWidgetAttributes as `prop:${K}`]?: EasycreditWidget[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "easycredit-accordion": LocalJSX.IntrinsicElements["easycredit-accordion"] & JSXBase.HTMLAttributes<HTMLEasycreditAccordionElement>;
            "easycredit-accordion-item": LocalJSX.IntrinsicElements["easycredit-accordion-item"] & JSXBase.HTMLAttributes<HTMLEasycreditAccordionItemElement>;
            "easycredit-base": LocalJSX.IntrinsicElements["easycredit-base"] & JSXBase.HTMLAttributes<HTMLEasycreditBaseElement>;
            "easycredit-box-flash": LocalJSX.IntrinsicElements["easycredit-box-flash"] & JSXBase.HTMLAttributes<HTMLEasycreditBoxFlashElement>;
            "easycredit-box-listing": LocalJSX.IntrinsicElements["easycredit-box-listing"] & JSXBase.HTMLAttributes<HTMLEasycreditBoxListingElement>;
            "easycredit-box-modal": LocalJSX.IntrinsicElements["easycredit-box-modal"] & JSXBase.HTMLAttributes<HTMLEasycreditBoxModalElement>;
            "easycredit-box-top": LocalJSX.IntrinsicElements["easycredit-box-top"] & JSXBase.HTMLAttributes<HTMLEasycreditBoxTopElement>;
            "easycredit-checkout": LocalJSX.IntrinsicElements["easycredit-checkout"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutElement>;
            "easycredit-checkout-bill-payment-timeline": LocalJSX.IntrinsicElements["easycredit-checkout-bill-payment-timeline"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutBillPaymentTimelineElement>;
            "easycredit-checkout-installments": LocalJSX.IntrinsicElements["easycredit-checkout-installments"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutInstallmentsElement>;
            "easycredit-checkout-label": LocalJSX.IntrinsicElements["easycredit-checkout-label"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutLabelElement>;
            "easycredit-checkout-privacy-approval": LocalJSX.IntrinsicElements["easycredit-checkout-privacy-approval"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutPrivacyApprovalElement>;
            "easycredit-checkout-totals": LocalJSX.IntrinsicElements["easycredit-checkout-totals"] & JSXBase.HTMLAttributes<HTMLEasycreditCheckoutTotalsElement>;
            "easycredit-express-button": LocalJSX.IntrinsicElements["easycredit-express-button"] & JSXBase.HTMLAttributes<HTMLEasycreditExpressButtonElement>;
            "easycredit-express-button-single": LocalJSX.IntrinsicElements["easycredit-express-button-single"] & JSXBase.HTMLAttributes<HTMLEasycreditExpressButtonSingleElement>;
            "easycredit-faq": LocalJSX.IntrinsicElements["easycredit-faq"] & JSXBase.HTMLAttributes<HTMLEasycreditFaqElement>;
            "easycredit-infopage": LocalJSX.IntrinsicElements["easycredit-infopage"] & JSXBase.HTMLAttributes<HTMLEasycreditInfopageElement>;
            "easycredit-logo": LocalJSX.IntrinsicElements["easycredit-logo"] & JSXBase.HTMLAttributes<HTMLEasycreditLogoElement>;
            "easycredit-merchant-manager": LocalJSX.IntrinsicElements["easycredit-merchant-manager"] & JSXBase.HTMLAttributes<HTMLEasycreditMerchantManagerElement>;
            "easycredit-merchant-status-widget": LocalJSX.IntrinsicElements["easycredit-merchant-status-widget"] & JSXBase.HTMLAttributes<HTMLEasycreditMerchantStatusWidgetElement>;
            "easycredit-modal": LocalJSX.IntrinsicElements["easycredit-modal"] & JSXBase.HTMLAttributes<HTMLEasycreditModalElement>;
            "easycredit-widget": LocalJSX.IntrinsicElements["easycredit-widget"] & JSXBase.HTMLAttributes<HTMLEasycreditWidgetElement>;
        }
    }
}
